### ISSUE TITLE
signature does not match - texttools v144 

### ISSUE THREAD

**Issue by rodrigotrovao** [franMarz/TexTools-Blender#100]
When trying downloading this TexTools 1.4.4 version, github page shows this: 

```
<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

**Comment by franMarz** [comment]
1ª Possible cause: Your clock is out of sync with the github servers.

To help protect against replay attacks, the current time can be used during the encryption/decryption process. If the time of the client and server disagree by more than the allowed amount, the process can fail and the request is rejected. This can also happen when you run a command in a virtual machine whose clock is out of sync with the host machine's clock. One possible cause is when the virtual machine hibernates and takes some time after waking up to sync the clock with the host machine.

On Linux or macOS, run date to check the time.

$ date

If your system clock is not correct within a few minutes, use ntpd to sync it.

$ sudo service ntpd stop
$ sudo ntpdate time.nist.gov
$ sudo service ntpd start
$ ntpstat

On Windows, use the date and time options in the Control Panel to configure your system clock.


2º Possible cause: Your operating system is mishandling secret keys that contain certain special characters.

github.com > profile > settings > developer settings > personal access tokens > workflow

If your secret key includes certain special characters, such as -, +, /, or %, some operating system variants process the string improperly and cause the secret key string to be interpreted incorrectly.

If you process your access keys and secret keys using other tools or scripts, such as tools that build the credentials file on a new instance as part of its creation, those tools and scripts might have their own handling of special characters that causes them to be transformed into something that github no longer recognizes.

The easy solution is to regenerate the secret key to get one that does not include the special character.

**Comment by franMarz** [comment]
No answer for a long time, so I assume the issue was resolved. Closing.

**Comment by rodrigotrovao** [comment]
Oh, sorry, im not used to git hubs issue thing. Pretty new to this.
I was downloading other scripts before and after this (all from directly
from browser, pushing download button in githubs website).
It gave this error *only* in yours. I dont believe the problem was mine.
Few days later, i went there, and downloaded it normally.
Maybe it was a github error. I was just trying to help anyway.

**Comment by franMarz** [comment]
It should have been a GitHub error. Thank you for trying to help, I hope this issue would guide someone in a good direction in the future. For now, it's just closed, but discoverable for everybody.
