### ISSUE TITLE
Is there a way to equalize texel density across several meshes ?

### ISSUE THREAD

**Issue by motorsep** [franMarz/TexTools-Blender#102]
I have a situation here.. I recall there is a tool in TexTool that unifies texel density on UV map of a mesh. However, I have hundreds of meshes and I need that not only to have proper texel density for each of them, but also for all meshes to have exact same texel density across the board. 
I assume I can join them all, go to UV Editor and unify texel density, and then manually separate them. 
What I am wondering about if there is a better, more automated way to go about it, something like transfer texel density from Active to Selected objects. 
Thanks.

**Comment by robleeper** [comment]
If I understand correctly, I was able to do this pretty easily. Select all objects in a scene, make sure they have a material applied - checker texture or whatever - then under UV Layout set and Apply the desired texel density. There wasn't any need to join meshes or do anything particularly fancy.

**Comment by franMarz** [comment]
> 
> 
> If I understand correctly, I was able to do this pretty easily. Select all objects in a scene, make sure they have a material applied - checker texture or whatever - then under UV Layout set and Apply the desired texel density. There wasn't any need to join meshes or do anything particularly fancy.

I assume this is the correct answer. Closing.

**Comment by motorsep** [comment]
Hmm.. Perhaps this was closed too early ?

I tried it and while it works perfectly on surfaces that are 90 degree to one another, it doesn't quite work otherwise. Maybe I am going wrong about the whole setup, but this is a video showing the issue:
https://www.youtube.com/watch?v=k4zwixKdun4
