### ISSUE TITLE
Sizes not correct

### ISSUE THREAD

**Issue by CraftoHohenvels** [franMarz/TexTools-Blender#104]
Followed the instructions (gif in docs) and the texture size doesn't fit on any object. E.g. I have 5 different objects that each have a different mesh in a different scale. I follow the steps and hm, all textures are at a different scale (they all use the same texture/material)

**Comment by franMarz** [comment]
Can you provide any example, screenshots, videos, example files or a further explanation? I think I'm not getting what you mean.

**Comment by franMarz** [comment]
Update to the latest version ([master](https://github.com/SavMartin/TexTools-Blender/archive/refs/heads/master.zip)), I think your problem could be solved now.

**Comment by franMarz** [comment]
Closed due to inactivity.
