### ISSUE TITLE
Simplify Some Code

### ISSUE THREAD

**Issue by ldo** [franMarz/TexTools-Blender#108]
I just noticed this in `op_color_assign.py`:

    if len(obj.data.vertex_colors) > 0 :
        vclsNames = [vcl.name for vcl in obj.data.vertex_colors]
        if 'TexTools_colorID' in vclsNames:
            obj.data.vertex_colors['TexTools_colorID'].active = True
        else:
            obj.data.vertex_colors.new(name='TexTools_colorID')
            obj.data.vertex_colors['TexTools_colorID'].active = True
    else:
        obj.data.vertex_colors.new(name='TexTools_colorID')

It can be simplified to:

    if 'TexTools_colorID' not in obj.data.vertex_colors :
        obj.data.vertex_colors.new(name='TexTools_colorID')
    obj.data.vertex_colors['TexTools_colorID'].active = True

I see one or two other similar circumlocutions in that file, too.

**Comment by franMarz** [comment]
Yes, some modules have plenty of these issues.

**Comment by franMarz** [comment]
This will be naturally addressed during the ongoing process of refactoring the modules. Closing.
