### ISSUE TITLE
Normal map appears with transparent holes.

### ISSUE THREAD

**Issue by ca3games** [franMarz/TexTools-Blender#109]
When I try to bake, I get holes on my normal map.

OS : Manjaro KDE 5.22
PC : AMD Ryzen 3 3200 G Vega 8 GPU
Blender 2.93.5

![textool error](https://user-images.githubusercontent.com/19626687/140463274-a794e9a8-daad-42a9-8e48-7fbe9d48d6cf.png)

**Comment by franMarz** [comment]
Could you share a simplified version of your file where this happens?

**Comment by ca3games** [comment]
Tried to replicate issue with a small multires modifier on a basic cube, got another issue instead.
Now the cube only bake front faces.

![textool error](https://user-images.githubusercontent.com/19626687/140483379-a1bc2829-3267-4c99-82c7-057cf69c022d.png)
[texttool square issue.tar.gz](https://github.com/SavMartin/TexTools-Blender/files/7481788/texttool.square.issue.tar.gz)

**Comment by franMarz** [comment]
Both objects, high and low, have to share the same position for a selection to active bake.
