### ISSUE TITLE
Create a single layer to assign vertex colors

### ISSUE THREAD

**Issue by cstfan** [franMarz/TexTools-Blender#111]
To avoid the restriction of the number of layers as mentioned in this [issue ](url)https://github.com/SavMartin/TexTools-Blender/issues/110#issue-1047913981
Is it possible to create a single layer to assign all the vertex colors as in this addon: https://www.youtube.com/watch?v=0lESUqZL4ko

**Comment by franMarz** [comment]
As far as i remember, we are doing that in the latest version of master. The approach should be to avoid the exception by disabling the possibility of assigning vertex colors if all 8 vertex colors channels are in use.

**Comment by cstfan** [comment]
Hi,
I just loaded the master, it's fine, the problem doesn't exist anymore, a unique Layer named TexTools_ColorID is created for the application of Vertex Colors.
You are great, I should have tested the master and not only the 1.4.4 release.
Thanks

**Comment by franMarz** [comment]
It's nice to be of help. Thank you.
