### ISSUE TITLE
What does "No valid meshes or UV maps" mean?

### ISSUE THREAD

**Issue by TristanHehnen** [franMarz/TexTools-Blender#117]
Hi!

I'm trying to apply the texel density to a couple of faces, using Blender 3.0. For the same object it works for some faces but for others it shows the message above. I'm new to texturing in in general and right now I have a hard time understanding what could be the issue here. 
I've unwrapped all faces of the object (smart uv project, in a couple of steps to produce individual islands), I've create the checker map with the arrows from textools and I've assigned this checker map material to the object. The oject itself is basically a box, where the top and bottom faces can get the texel density assigend. However, the sides are not so cooperative. In the viewport, the texture map is visible also on the non-cooperative faces and shows the appropriate section of the texture. Thus, I assume the basics are there and I'm doing something wrong somewhere else.
For a second object, also a box, none of the faces allow a texel density to be assigned to them.

Furthermore, how does textools know how many pixels per edge are the appropriate resolution? For instance, my test box is 1 m long and about 0.6 m wide and I would like a resolution of 2048 pixel per meter. So I chose a 2048 by 2048 texture and unwrapped the top faces. Then, automatically the longest side is filling the whole length of the texture, which should be my desired resolution of 2048 pixels per 1 m. However, when I take the density with the eyedropper it tells me the resolution is 2040.53. I've applied the rotation and scale in object mode, just to be sure.

Could you point me to what I might be doing wrong here?

Thanks,
Tristan

**Comment by franMarz** [comment]
Can you please provide the file you are using with the problematic faces selected?

**Comment by TristanHehnen** [comment]
I've attached the file here.

[Kitchen_Textools.zip](https://github.com/SavMartin/TexTools-Blender/files/7697315/Kitchen_Textools.zip)

Thanks!

**Comment by franMarz** [comment]
Thank you, I'll review it. At first, I see that something is happening with "UV Sync Selection" ON, that is for sure. I'll compare this with the behaviour in 2.93.

**Comment by franMarz** [comment]
> Furthermore, how does textools know how many pixels per edge are the appropriate resolution? For instance, my test box is 1 m long and about 0.6 m wide and I would like a resolution of 2048 pixel per meter. So I chose a 2048 by 2048 texture and unwrapped the top faces. Then, automatically the longest side is filling the whole length of the texture, which should be my desired resolution of 2048 pixels per 1 m. However, when I take the density with the eyedropper it tells me the resolution is 2040.53

When you get or apply a Texel Density from/to a group of faces, not every one gets the same density unless they have no distortion at all. The overall area is what matters, so that some faces would get more density and others less than your target density. Furthermore, some face area calculation may fail if you have ngons, like in your example.

**Comment by TristanHehnen** [comment]
I tried out the new version, it seems to work now. 

Alright, so that means I need to pay attention to avoid ngons and distortion of the faces.

Thank you very much!
