### ISSUE TITLE
should this work in 2.82?

### ISSUE THREAD

**Issue by gswartz777** [franMarz/TexTools-Blender#12]
I just got blender, v 2.82.  When I make a selection of faces, many of the options under UV Layout are greyed out.  I wanted to run rectify on this selection, but no love.  Should this work with 2.82?  In addition, if I select all of my faces in the 3d view and click on anything else like crop of fill, nothing happens.  It appears that nothing works.

![textools](https://user-images.githubusercontent.com/4447393/74614175-9f61b380-50e3-11ea-8048-327a9baa513a.PNG)

**Comment by Brotherarchii** [comment]
Bake not work in Blender 2.82

**Comment by SavMartin** [comment]
Try installing this one: https://github.com/SavMartin/TexTools-Blender/releases/download/TexTools_2.80/textools.zip

**Comment by franMarz** [comment]
You have to deactivate the UV Sync Selection on the top left corner of the UV Editor. Also, there is a line on the code of textool that is wrong, with it fixed, a red button should appear on the panel you are showing just for warning you about the the syncing being on and as an alternate method for turning it off. Here in attaching the fixed python file, if you want, paste it on the TexTools-Blender-master folder.
[__init__.zip](https://github.com/SavMartin/TexTools-Blender/files/4580508/__init__.zip)

**Comment by AvisParadocs** [comment]
Can you tell what exact lines it is?

**Comment by franMarz** [comment]
Sure: 243
Should be:
`    bl_idname = "uv.op_disable_uv_sync"`
Nothing fancy, I got a warning in the console of Blender when switching between UV Sync Selection on and off

**Comment by SavMartin** [comment]
Fixed.
