### ISSUE TITLE
Generate UV mesh doesn't seem to work in 3.0

### ISSUE THREAD

**Issue by MeshVoid** [franMarz/TexTools-Blender#121]
Hi! I get this error whenever I press generate UV mesh in blender 3.0 
![image](https://user-images.githubusercontent.com/35863328/148914181-b49b513d-6058-4552-b018-345c8c850f2b.png)

**Comment by SavMartin** [comment]
Its working for mi with last version of Textools

**Comment by franMarz** [comment]
Same, please download and use [the zipped code from the main/master branch](https://github.com/SavMartin/TexTools-Blender/archive/refs/heads/master.zip) and install it as if it were a release.
