### ISSUE TITLE
Create UV Mesh python error bpy.ops.uv.select_split.poll() failed, context is incorrect

### ISSUE THREAD

**Issue by 3dhype** [franMarz/TexTools-Blender#122]
Hi there.

Software used: Blender 3.0.0
TexTools 1.4.4

Python: Traceback (most recent call last):
  File "C:\Users\<user>\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\TexTools-Blender-master\op_meshtex_create.py", line 26, in execute
    return create_uv_mesh(self, context, bpy.context.active_object)
  File "C:\Users\<user>\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\TexTools-Blender-master\op_meshtex_create.py", line 70, in create_uv_mesh
    bpy.ops.uv.select_split()
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.uv.select_split.poll() failed, context is incorrect

location: <unknown location>:-1

**Comment by franMarz** [comment]
Have you got the 1.4.4 release installed or the latest version from [master/main](https://github.com/SavMartin/TexTools-Blender/archive/refs/heads/master.zip)?
If the latest, I don't know from where you are executing the Create UV Mesh utility to get a bad context call. For me, it works in the 3d view menu, in the UV editor, and in object, edit mode. Can you elaborate how you use the utility?

**Comment by 3dhype** [comment]
Yes, I think I just downloaded it just a couple of days ago from here.
I will recheck. I pushed the Uv to Mesh in the UV Editor.

**Comment by franMarz** [comment]
So, have you managed to isolate or solve the problem?

**Comment by franMarz** [comment]
Closed due to inactivity
