### ISSUE TITLE
Texel density, combined mode

### ISSUE THREAD

**Issue by hitrpr** [franMarz/TexTools-Blender#123]
This mode described as scaling islands together, but actually it do not scale em together as expected.
It scales each island individually to target TD, but relatively to common origin instead individual origins.

It is easy to test it:
Add 2 cubes, join them, scale UV for one of them, try to apply combined TD. It will shift islands relatively each other, instead scaling them together.

initial UV:
![изображение](https://user-images.githubusercontent.com/21099918/150779189-6ce68644-0297-4ecf-a7be-fec5922ccaca.png)
Pick average, apply combined. UV should stay the same as far as there is two islands and in sum they have average TD.
But result looks like this: individual TD became the same and islands was shifted
![изображение](https://user-images.githubusercontent.com/21099918/150779403-e5839049-a4f0-405c-b3e8-06b099463f96.png)

Proper algorithm is: scale New_Texel_Density/Average_Texel_Density

**Comment by franMarz** [comment]
It is working properly for me in the latest version from [master/main](https://github.com/SavMartin/TexTools-Blender/archive/refs/heads/master.zip). Please check that you have it installed.

**Comment by franMarz** [comment]
Have you checked your installed version, is the problem still happening?

**Comment by hitrpr** [comment]
> Have you checked your installed version, is the problem still happening?

Checked, now it works properly, thanks.
