### ISSUE TITLE
activating addon crashes blender 3.x

### ISSUE THREAD

**Issue by Skyemou5** [franMarz/TexTools-Blender#125]

**Comment by franMarz** [comment]
Please make more clear in which version of Blender is the crash happening. 3.1 onwards are versions under depelopment and could be that the problem is with Blender, not with the addon.

**Comment by Skyemou5** [comment]
I'm on linux. But I've tried several times with clean installs of the addon with blender 3.0, 3.01, and 3.1 with the same results

**Comment by franMarz** [comment]
We need confirmation from other people trying TexTools on linux about this. For me is hard to provide support for issues specific of a platform other than Windows atm.

**Comment by Nassflow** [comment]
Yo can modify just a line in "op_bake.py" to make it works
![imagen](https://user-images.githubusercontent.com/101663032/158437947-630ac12f-fbe0-437d-a720-ea65302246ce.png)

**Comment by franMarz** [comment]
> Yo can modify just a line in "op_bake.py" to make it works ![imagen](https://user-images.githubusercontent.com/101663032/158437947-630ac12f-fbe0-437d-a720-ea65302246ce.png)

If you use the version from [master](https://github.com/SavMartin/TexTools-Blender/archive/refs/heads/master.zip), you don't need to do that, right?

**Comment by Nassflow** [comment]
No, you don't need it on master, it was just for 1.4. They've allready solved, but it didn't know it

**Comment by franMarz** [comment]
Closing due to lack of constrast from other Linux users.
