### ISSUE TITLE
not default gpu

### ISSUE THREAD

**Issue by INU-ez** [franMarz/TexTools-Blender#130]
![image](https://user-images.githubusercontent.com/83541050/155288734-5f2ee785-b22a-407e-9475-2eb871537112.png)
![image](https://user-images.githubusercontent.com/83541050/155288873-83cfe5c6-0251-4513-8e57-9ffdfc543940.png)

**Comment by INU-ez** [comment]
Set default gpu
But it doesn't work

**Comment by wookieejedi** [comment]
Have you tried current main branch? I had some bugs that were fixed when switching to the main branch. 
![image](https://user-images.githubusercontent.com/14077810/155326052-fc81b33d-f43c-4b10-81cb-86c9611c68e6.png)

**Comment by franMarz** [comment]
When using CUDA, windows task manager doesn't show GPU usage there. You have to switch to the Performance tab, GPU, and select one of the charts as CUDA, but bear in mind that certain GPU drivers aren't compatible with Windows monitoring CUDA activity and most likely you won't have that option either. In any case, change back and forth between CPU and GPU just to check if the render times change.
