### ISSUE TITLE
Textools baking bug

### ISSUE THREAD

**Issue by eE1ght** [franMarz/TexTools-Blender#135]
Textools can't properly bake Base Color, Metallic, Specular (pretty much everything that isn't in the native Blender bake tool like roughness, normals, transmission) if there are 2 or more Principled BSDFs in the same material connected to the "Material output" node with a "Mix Shader" or "Add Shader" node. It will only bake the Principled BSDF that has the name exactly as "Principled BSDF". If its name is anything other than that like "Principled BSDF3" it will say "BSDF nodes needed" below the Bake button and it will grey it out. If there is a Principled BSDF with the name "Principled BSDF" and another with the name "12345" connected to a "Material output" node via a "Mix Shader" node it will only bake the nodes connected to the BSDF that has the name "Principled BSDF". This happens with every Blender version.
![1](https://user-images.githubusercontent.com/102018047/159224919-4aea86fd-b557-4a39-87a7-201314fad12d.png)
![2](https://user-images.githubusercontent.com/102018047/159224936-36be9b57-29d4-43b4-ae9f-69abf2585646.png)
![3](https://user-images.githubusercontent.com/102018047/159224943-3658db83-0634-4c74-bf91-614a061f67bb.png)

**Comment by franMarz** [comment]
This is a known limitation and, for now, I don't see a way of improving this for every baking mode. Anyway, I'll think about it.

**Comment by franMarz** [comment]
Not getting confused by the Principled BSDF node name should be a must, that's for sure.

**Comment by eE1ght** [comment]
It's one of the most useful addons for sure, thank you for continuing to develop it.

**Comment by eE1ght** [comment]
@franMarz Could you please delete this issue?

**Comment by franMarz** [comment]
Ok, I'll just take note of that Principled BSDF node name issue

**Comment by eE1ght** [comment]
I would appreciate it if you could delete this issue altogether instead of closing it.

**Comment by franMarz** [comment]
I can't, maybe @SavMartin ? Have you checked your options? Being the creator of the issue, if you can't delete it, maybe we neither.
