### ISSUE TITLE
Pick is removing the First Selected Object in a Selection of Objects

### ISSUE THREAD

**Issue by ABugNamedBeetle** [franMarz/TexTools-Blender#136]
https://user-images.githubusercontent.com/62416701/159980792-ea06194b-949a-424c-af99-9bf7ed3780bc.mp4

The issue is very simple if I select two objects and try to pick the Texel Density, it removes the first selected object.

At 0:05 - **ico sphere** is selected first and then the cube
At 0:12 - I tried to pick the TD of **ico sphere**, UV disappeared and was removed from the EDIT MODE

At 0:17 - the **cube** is selected first and then the ico sphere
At 0:24 - again I tried to pick the TD of **ico sphere**, UV disappeared and was removed from the EDIT MODE

I want the UV to stay in the editor and both of the objects in EDIT MODE

**Comment by franMarz** [comment]
That is already solved in [master](https://github.com/SavMartin/TexTools-Blender/archive/refs/heads/master.zip)
