### ISSUE TITLE
Applying TD is Splitting the UV faces

### ISSUE THREAD

**Issue by ABugNamedBeetle** [franMarz/TexTools-Blender#137]
https://user-images.githubusercontent.com/62416701/161120219-4baee3ed-0ad7-484d-981d-432c3d37dda5.mp4

In Ver 1.5, while applying Set TD, is applying only to connected faces, not to all linked faces. In this process, it is splitting linked faces.

In Ver 1.4.3 it does work.

**Comment by franMarz** [comment]
It was just changed to behave like this. Texel density should be picked from and apply to the selection, not the entire island, is coded to work in the selected faces only and I think is the right way to go. Selecting all linked faces before applying any TexTool utility is as easy as typing Ctrl+L.

**Comment by ABugNamedBeetle** [comment]
yes, but it is not working as intended, as you said only selected faces will be scaled. But as in the current logic is it scaling the selected and the adjacent connected faces and splitting the island.

**Comment by franMarz** [comment]
This is because you are using the Shared Location in the Sticky Selection Mode. If you disable that, it will behave as expected.
