### ISSUE TITLE
Rectify produces inconsistent results with mirrored mesh/uvs

### ISSUE THREAD

**Issue by jangofett890** [franMarz/TexTools-Blender#144]
Make a mirrored mesh.
Apply the mirrored modifier
UV Unwrap it.
select an edge loop from one side, select mirror.
Extend selection to get faces.
Rectify in uv, and you get two widely different rectangles when you should get two identical rectangles.
![image](https://user-images.githubusercontent.com/2407092/169227611-ceae0f33-3ffa-45f9-a72b-489170266019.png)
![image](https://user-images.githubusercontent.com/2407092/169227715-89e11f47-9094-4536-823c-288c4283fcdb.png)
![image](https://user-images.githubusercontent.com/2407092/169227800-e2c0b2e7-baba-4da7-b266-28093b3de967.png)

**Comment by franMarz** [comment]
Rectify is a complex utility. If you want a similar result, you must know that the active vertex is really important. I would apply Rectify to each island one by one, selecting an active vertex that is in a similar or mirrored position respect each other. But it is not guaranteed that you'll get what you need. 
We use the code from the UV Squares addon for Rectify, we improved it to make it faster, but making it work perfectly for every situation is almost impossible.
