### ISSUE TITLE
Inverted Paddings in Baked Map using Material ID

### ISSUE THREAD

**Issue by gotanidea** [franMarz/TexTools-Blender#149]
Hi, I have a geometry with two materials, that are converted into five materials using TexTools, but the paddings are inverted in the baked map. Please find the Blender file from this link: [https://mega.nz/file/4jxWXbJA#7XRkiaOEQPT6VxKTRKtD1ezUdI2soqdfjqArs6A0YNQ](url)

If you have time, could you please take a look? Thanks

[https://ibb.co/Z6qQF1W](url)

**Comment by franMarz** [comment]
What do you mean with "The paddinds are inverted"? The only weird thing I see are borders in some islands of different color, caused by faces that are not unwrapped, but projected from the side as lines in the perimeter of those islands.

**Comment by franMarz** [comment]
You're using 5 color IDs but only have 2 maerials assigned, and are using the "material ID" baking mode that won't respect those colors anyway, because it assigns new colors to the different assigned materials automatically (it is meant to be used with material with textures,as a way of creating a mask by material or something like that). If you want the same color in the bake that in the model, use the "diffuse" or the "base color" baking mode.

**Comment by gotanidea** [comment]
> What do you mean with "The paddinds are inverted"? The only weird thing I see are borders in some islands of different color, caused by faces that are not unwrapped, but projected from the side as lines in the perimeter of those islands.

I unwrapped the geometry using Smart UV Project, but the border colors in some UV islands are still not the same as the colors of the UV islands: [https://ibb.co/crDFsPm](url) . I guess generated colors will always be like that on some UV islands, if we use TexTools.

**Comment by gotanidea** [comment]
> You're using 5 color IDs but only have 2 maerials assigned, and are using the "material ID" baking mode that won't respect those colors anyway, because it assigns new colors to the different assigned materials automatically (it is meant to be used with material with textures,as a way of creating a mask by material or something like that). If you want the same color in the bake that in the model, use the "diffuse" or the "base color" baking mode.

Where is the "diffuse" or the "base color" baking mode option in TexTools panel? I can't find it

**Comment by franMarz** [comment]
> Where is the "diffuse" or the "base color" baking mode option in TexTools panel? I can't find it

![FwCNwey](https://user-images.githubusercontent.com/58062362/187972002-4e3cf28e-60b7-41f2-81ef-b3881609e468.jpg)

**Comment by franMarz** [comment]
> I unwrapped the geometry using Smart UV Project, but the border colors in some UV islands are still not the same as the colors of the UV islands: [https://ibb.co/crDFsPm](url) . I guess generated colors will always be like that on some UV islands, if we use TexTools.

Textools does nothing with the padding color, that is the Blender baking system itself, but I doubt it's failing either. I guess is a bad unwrap, use the "Zero" utility of textools (at the bottom of the UVLayout panel) to detect whether or not some faces are badly projected.

**Comment by gotanidea** [comment]
> > I unwrapped the geometry using Smart UV Project, but the border colors in some UV islands are still not the same as the colors of the UV islands: [https://ibb.co/crDFsPm](url) . I guess generated colors will always be like that on some UV islands, if we use TexTools.
> 
> Textools does nothing with the padding color, that is the Blender baking system itself, but I doubt it's failing either. I guess is a bad unwrap, use the "Zero" utility of textools (at the bottom of the UVLayout panel) to detect whether or not some faces are badly projected.

Both "diffuse" and the "base color" baking mode options generate the same weird border colors, even though the geometry is unwrapped using Smart UV Project. The "Zero" utility of TexTools also doesn't detect any badly-projected face.

I will just make the colors manually. Thanks

**Comment by franMarz** [comment]
Can you bake the diffuse texture directly in Blender, not by using the addon? The borders should appear as well and we can close this issue.

**Comment by gotanidea** [comment]
> Can you bake the diffuse texture directly in Blender, not by using the addon? The borders should appear as well and we can close this issue.

I changed Render Properties > Bake > Margin > Type to Extend and the weird border colors disappear. Thanks

**Comment by franMarz** [comment]
I think that option changed in recent versions of Blender and we should expose it in the TexTools Bake panel. It's nice you found it.
