### ISSUE TITLE
Bake not work

### ISSUE THREAD

**Issue by Brotherarchii** [franMarz/TexTools-Blender#15]
Bake not work in Blender 2.82

**Comment by SavMartin** [comment]
Its works perfectly.
![imagen](https://user-images.githubusercontent.com/30030642/76209142-10831b00-61f9-11ea-8503-a77b4076efe4.png)

**Comment by SavMartin** [comment]
Maybe yo didint download the addon from here : https://github.com/SavMartin/TexTools-Blender/releases/download/TexTools_2.80/textools.zip

**Comment by Brotherarchii** [comment]
Thanks! Work!
