### ISSUE TITLE
Normal Map textures are linked to Emission input of the Principled BSDF shader.

### ISSUE THREAD

**Issue by Akhura** [franMarz/TexTools-Blender#153]
Recently found the minor issue, that when previewing the normal map textures after baking, the script inserts it into Emission input of the Prinicpled BSDF shader.
The blender version is irrelevent in this situation, I guess, but the issue was found since Blender 3.3 and the latest version of TexTools is installed
![image](https://user-images.githubusercontent.com/88729252/206592068-022c462a-1ed7-4b88-951e-0dfb23a0f95e.png)

**Comment by franMarz** [comment]
When you use the Preview Texture utility, for any texture, what the script does is connect it to the emission slot, so you can view it in the object in the 3D view. Maybe for Normal maps it may be more useful to link it to the Normal channel of the shader. Anyway, we should reconsider how all of this works, linking this to the issue #89

**Comment by Akhura** [comment]
> When you use the Preview Texture utility, for any texture, what the script does is connect it to the emission slot, so you can view it in the object in the 3D view. Maybe for Normal maps it may be more useful to link it to the Normal channel of the shader. Anyway, we should reconsider how all of this works, linking this to the issue #89

Oh..I see, well it kinda makes sense now - like the preview function in Marmoset.
![image](https://user-images.githubusercontent.com/88729252/206643675-e804809e-37c3-44dd-85fb-e619685e26cf.png)
Though, I guess it'd be nicer to plug it into "Base color" channel.. like the other baked maps, if only for the pure texture preview purpose.
Thanks for the reply!
