### ISSUE TITLE
Pattern Creating Operator issue

### ISSUE THREAD

**Issue by Akhura** [franMarz/TexTools-Blender#154]
Tracked another 2 thingies: operators for creating triangle and hexagonal patterns
Also Blender 3.4
![blender_Xv4L83OSJ7](https://user-images.githubusercontent.com/88729252/206792441-6b4e43f1-4f75-4240-93f2-cc1afb9c0c8f.png)
![blender_5wIGvcdrfH](https://user-images.githubusercontent.com/88729252/206792447-a1b7410e-d322-4811-90d0-8b922d54bb8d.png)
And guess that's all..all the other operators are working well

**Comment by franMarz** [comment]
Thank you for your reports!

**Comment by franMarz** [comment]
That was already solved, use the latest version of TexTools from master ([https://github.com/SavMartin/TexTools-Blender/archive/refs/heads/master.zip](https://github.com/SavMartin/TexTools-Blender/archive/refs/heads/master.zip)), the latest release is outdated.
Thank you anyway!
