### ISSUE TITLE
(Bug) Cannot create checker map

### ISSUE THREAD

**Issue by maximum-dino** [franMarz/TexTools-Blender#156]
It will not allow me to create a checker map. The option is greyed out. There is nothing I can do, I've tried to add and readd the addon, I've tried so many things. I asked some people if they knew what the problem was and they said it overall was just a very glitchy addon. Really disappointing, hope it gets fixed soon.
![Screenshot (5)](https://user-images.githubusercontent.com/122641137/212443674-a76856b0-5d28-47d5-a568-fec5eb12b60c.png)

**Comment by franMarz** [comment]
Test the [latest version of TexTools](https://github.com/SavMartin/TexTools-Blender/archive/refs/heads/master.zip) and tell me if it works

**Comment by franMarz** [comment]
@maximum-dino I close issues I think are solved if we don't get a response to a patch in a week. Please answer my question before that.

**Comment by franMarz** [comment]
Closed due to inactivity.
