### ISSUE TITLE
не работает в блендере 3.4.1

### ISSUE THREAD

**Issue by torgov85** [franMarz/TexTools-Blender#158]
![image](https://user-images.githubusercontent.com/125745349/221410082-4dd96599-9f44-4914-949d-c4c24be274e9.png)

**Comment by franMarz** [comment]
Prior to 3.4.1, most node names where not translated internally. They've changed that in recent versions of Blender. Maybe we can find a different way to point to nodes while altering the materials.
In the meantime, if you can, use Blender in English and this addon and probably others will behave fine.
