### ISSUE TITLE
name 'function' not defined

### ISSUE THREAD

**Issue by Athomield** [franMarz/TexTools-Blender#16]
i get this issue after i tried to use rectify. i'm selecting multiple meshes. when i was on select all verts it started behaving stangely so i selected one particular part with Ctrl+L and it gave me this error.
![rtretreter](https://user-images.githubusercontent.com/7095418/78974054-72dd7d00-7b11-11ea-9fac-eab4f9d18281.png)

**Comment by SavMartin** [comment]
Delete that one , and install this one :https://github.com/SavMartin/TexTools-Blender/releases/download/TexTools_2.8x/Textools.zip
