### ISSUE TITLE
No 'Displace' mode in the  mode selection window

### ISSUE THREAD

**Issue by sofiks99** [franMarz/TexTools-Blender#160]
![image](https://user-images.githubusercontent.com/128513388/226688900-0d5f9a00-2e2f-4349-aa6c-fc82effe0e9d.png)

**Comment by franMarz** [comment]
Blender doesn't support general Displacement baking atm, only from multires, so we can't have it either, not at least in a non-heavily-hacky and limited way. Sorry.
