### ISSUE TITLE
Not working with Blender 3.5

### ISSUE THREAD

**Issue by kekkorider** [franMarz/TexTools-Blender#162]
Hello there,

The add-on does not work with Blender 3.5. There are no errors or whatsoever, the TexTool panel simply doesn't show up 🤔

![screenshot](https://github.com/SavMartin/TexTools-Blender/assets/5191941/e7f2af3a-4483-450b-9da8-e7c0a463a909)

**Comment by franMarz** [comment]
We're on Textools 1.5.1 now, install the latest version [from here](https://github.com/SavMartin/TexTools-Blender/archive/refs/heads/master.zip) and tell us whether it works or not.

**Comment by kekkorider** [comment]
My bad, I downloaded the add-on [from the website](http://renderhjs.net/textools/blender/) which still has the 1.3 version and didn't even think about looking for a newer version here on the repo.

Confirming that it works! 🦄
