### ISSUE TITLE
Blender 3.5 Mix node Issue

### ISSUE THREAD

**Issue by 0nnix** [franMarz/TexTools-Blender#164]
seems like this addon does not familiar with new mix node in blender 3.5. when textures is mixed,  with new version of mix node in blender's 3.5.  baking metallic, roughness base color etc with new mix node makes weird results - it bakes only one of connected maps to that mix node
It works with old mix node(legacy)
so for now I have added mix node (legacy)  from old version of blender into a group and group marked as asset to have ability to quick add mix node that can be utilized by textools
It would be nice to have support for a new mix node in blender 3.5 to bake mixed textures

**Comment by 0nnix** [comment]
blender ubdated to 3.6 and group node trick doesnot work for me anymore so found another workaround. As I like to bakein ambient occlusion map into a base color but new mix node do not allow me to do it via textools so at first I found out that  just putting  separate  and combine color between principled bsdf and mix node  this is allowing me to bake base color as ussual and plaing more with it i ended up adding several cutpoints on connection between mix node and principle bsdf base color and it also works 
![image](https://github.com/SavMartin/TexTools-Blender/assets/115031661/d96114b9-53da-4a5a-a4b5-e095be894a7d)

![image](https://github.com/SavMartin/TexTools-Blender/assets/115031661/d5d5b986-3c93-446b-a5a0-0fceaeca5970)

**Comment by franMarz** [comment]
I can't reproduce for any input combination in Blender 4.0 and current TexTools. Maybe an old issue within Blender that now is solved. Closing, please reopen if it still happens for you.
