### ISSUE TITLE
Rubber Tweak for arms and legs automatically set to 1 after running script

### ISSUE THREAD

**Issue by PanicPug** [franMarz/TexTools-Blender#167]
When using the Prepare Rig for Unity Script on the generated Rigify Rig, the Rubber Tweak value for tweak bones in the middle of each arm and leg bone (e.g. upper_arm_tweak.L.001 and forearm_tweak.L.001 for the left arm) is automatically set to 1. 
As a result the arms and legs bend when their respective child bones are rotated, due to the DEF bones being turned into Bendy Bones (or the bendy part being activated on these bones).

**Comment by franMarz** [comment]
Not related to this addon. Closing.

**Comment by PanicPug** [comment]
Oh sorry, I don't know why Git jumped to this add-on and how I missed that I'm on the wrong page.
