### ISSUE TITLE
Blender 4.0 Update

### ISSUE THREAD

**Issue by mertcanserim** [franMarz/TexTools-Blender#173]
Unfortunately, this plugin does not work in version 4.0 of blender, we are waiting for an update to the plugin.

**Comment by michelepoletto3d** [comment]
Same here! Please update! I would be happy to offer you a tip for updating this essential tool!

**Comment by mertcanserim** [comment]
franMarz made a commit. If you download the repository as zip, it will work, but there are some errors in some operations, for example, I get such an error when changing the size of the uv map;

![image](https://github.com/SavMartin/TexTools-Blender/assets/74680885/f2cc081b-4275-41c1-b601-a7b80f0015c4)

**Comment by mertcanserim** [comment]
I get this error when using the rectify operation;

![image](https://github.com/SavMartin/TexTools-Blender/assets/74680885/c2e950a6-7bf7-411d-905e-920484d2c0c1)

**Comment by mertcanserim** [comment]
I get this error when using the unwrap operation;

![image](https://github.com/SavMartin/TexTools-Blender/assets/74680885/29a0aa6f-b44b-4425-911e-15093d3bbf03)

**Comment by mertcanserim** [comment]
But texture baking generally works.

**Comment by RobAllsopp-hub** [comment]
Im am also having issues using textools 
![textools error](https://github.com/SavMartin/TexTools-Blender/assets/61701839/ea9a78c4-7b59-4c4b-898f-cce92ef06e54)

**Comment by franMarz** [comment]
Thank you for reporting. Fixed and closed because this issue is too generic. For issues related to the new Blender, please open more specific tickets or add info to the ones already open.
