### ISSUE TITLE
Cant see the window to use TexTools?

### ISSUE THREAD

**Issue by TobyTruePlayers** [franMarz/TexTools-Blender#176]
I have the addon enabled latest version, in UV Editing but cannot see the Tex Tools window anywhere, wondered if i could get some help
![image](https://github.com/SavMartin/TexTools-Blender/assets/131363815/f4242382-a30d-41f8-a14f-38356eeeacef)

Thanks

**Comment by TobyTruePlayers** [comment]
Isssue resolved, downloaded and tried latest 2 versions on this site and wouldnt work. 
https://renderhjs.net/textools/blender/log.html

Downloaded most recent on Github and worked, not sure what the difference is but maybe site version is outdated/ broken? Wouldnt show atall but recent git version worked straight away.

**Comment by franMarz** [comment]
The website version of this add-on is as old as Blender 2.79, @SavMartin created this repository 4 years ago to make it compatible with 2.80 and newer versions of Blender.
