### ISSUE TITLE
Cant install tex tools in blender 4.0

### ISSUE THREAD

**Issue by petcson** [franMarz/TexTools-Blender#177]
![image](https://github.com/SavMartin/TexTools-Blender/assets/17130183/fc01ddfe-902a-4d11-be53-0f3a56ce8763)
after choosing the textools zip i try to click the check box and get this error.

**Comment by CaseyWagner** [comment]
Replicated here as well. Reinstalled 3.6 LTS and installed the same zip file in it to be sure it was not an issue with the downloaded file.

**Comment by franMarz** [comment]
Always install [the latest version from master](https://github.com/SavMartin/TexTools-Blender/archive/refs/heads/master.zip). If that doesn't work, please add a new comment here, but don't close this issue for now as it may help others.

**Comment by CaseyWagner** [comment]
Aha! Thanks so much. I didn't realize the master stream was functionally different from the release stream.
Installed without issue!

**Comment by franMarz** [comment]
Closing ahead of the next release.
