### ISSUE TITLE
"Straight" in Blender 4.0 doesn't work correctly

### ISSUE THREAD

**Issue by Slimek1** [franMarz/TexTools-Blender#178]
Previously, the 'straight' option straightened the selected loop and relaxed the rest of the island along with it. Now when you use it, the loop that you want to straighten detaches from the island.

Before clicking 'straight'
![image](https://github.com/SavMartin/TexTools-Blender/assets/14257834/4d978c58-67ad-4dc0-9ad8-e600ee858400)

After
![image](https://github.com/SavMartin/TexTools-Blender/assets/14257834/0470a393-da22-48a1-991e-c1d2ea26660d)

**Comment by franMarz** [comment]
Thank you for the report.

**Comment by franMarz** [comment]
Fixed by [a9dcd3a](https://github.com/franMarz/TexTools-Blender/commit/a9dcd3aac62ae7f72734270b3d2503254f8367fd)
