### ISSUE TITLE
I got errors when I tried to enable the add-on.

### ISSUE THREAD

**Issue by a-PRICUM** [franMarz/TexTools-Blender#18]
<img width="917" alt="2020-05-11 (5)" src="https://user-images.githubusercontent.com/45105928/81506049-c28caf80-932e-11ea-9100-3c1880fc87ff.png">

Could you tell me what to do with this error, please?

**Comment by yuukiit** [comment]
Same error shown on my environment too.
But, it succeeded when after restart Blender!
