### ISSUE TITLE
Please use Releases feature so we can get email updates on new versions

### ISSUE THREAD

**Issue by slrgt** [franMarz/TexTools-Blender#181]
Hi, Great addon! It would be really useful if you used the Releases feature so we can get email updates on new versions

**Comment by franMarz** [comment]
There are a few issues I want solved before publishing the next release, I'll activate the section again then. The last release was a year ago and it was confusing for a lot of people who opted to download it instead the master package.
In the future I'll publish releases more often, as soon as any important bug is tackled.
