### ISSUE TITLE
In Blender 4.0 can't make map larger than 512x512

### ISSUE THREAD

**Issue by bigp3rm** [franMarz/TexTools-Blender#187]
Trying to make a map 2048x2048 and it only creates 512x512.

**Comment by franMarz** [comment]
I can bake any map resolution without issues, I'll need more info. Can you record the screen while setting up the bake?

**Comment by SteveBritton73** [comment]
bigp3rm might be referring to the checker map grid textures? In Blender 4 the checker grid textures seem to be limited to 512x512.

**Comment by xWaszka** [comment]
> bigp3rm might be referring to the checker map grid textures? In Blender 4 the checker grid textures seem to be limited to 512x512.

Yup, I have the exact same problem, can't make checker map any larger than 512x512

**Comment by bigp3rm** [comment]
In the flipped normals master class I'm following the instructor is able to achieve a larger checker map somehow.

**Comment by franMarz** [comment]
Checker map resolutions are fixed since 1.6, they are used in the add-on for UV flow check in 3D space, I refactored the code for that and I won't change it for a number of reasons which you can find in the 1.6 release notes. You can change the checker maps manually as they are located inside resources/materials_3.0.blend.

**Comment by leryss** [comment]
you dont have many friends am i right ?

**Comment by artistCDMJ** [comment]
You can use a free disconnected image texture node with a generated image
using UV grid or color grid and select that to check in solid mode. This
will allow you to change the size of the check image in the node editor
side bar n panel.
