### ISSUE TITLE
No texture displayed when cycling checker map to "gravity map"

### ISSUE THREAD

**Issue by Boozebeard** [franMarz/TexTools-Blender#189]
I think the linking to the image is broken in the material? if I go into the shader nodes and relink the image, to the image file in the plugin resources, it works.

Also, questions, is there a way to scale/tile the checker maps?

**Comment by franMarz** [comment]
Please add your OS, Blender version and TexTools version to the issue. It works for me without issue.
A tiling option would be great for sure, I was considering adding it in the last refactor. I'll look into it when I have time.

**Comment by franMarz** [comment]
I can't reproduce it. Can you test again after removing the 'checker_map_gravity.png' image from the resources folder and overwritting the 'materials_3.0.blend' with the following file, which have the gravity image packed in it?
[materials_3.0.zip](https://github.com/franMarz/TexTools-Blender/files/14307787/materials_3.0.zip)

If it still fails, please add your OS, Blender version and TexTools version to the issue. Is there any error message in the Blender console?

And yes, a tiling option would be great for sure, I was considering adding it in the last refactor. I'll look into it when I have time.

**Comment by Boozebeard** [comment]
That fixed it :)
