### ISSUE TITLE
Align Edge seems not functioning after 1.4.4

### ISSUE THREAD

**Issue by Akhura** [franMarz/TexTools-Blender#190]
Blender 3.6.8
TexTools 1.6
As the title says, Align Edge seems to be a little bit broken after recent updates
Short proof-video

https://github.com/franMarz/TexTools-Blender/assets/88729252/62fd9d61-f58b-4d06-8366-1300d8d4f147

**Comment by franMarz** [comment]
I can't reproduce in Blender 3.6.8 with [latest master](https://github.com/franMarz/TexTools-Blender/archive/refs/heads/master.zip) of TexTools (version 1.6.1 shown in the add-on preferences)

**Comment by Akhura** [comment]
Confirmed, latest master "Align Edge" working as it should, thanks!
