### ISSUE TITLE
Problem with "Get Texel Density" and "Apply Texel Density"

### ISSUE THREAD

**Issue by heclak** [franMarz/TexTools-Blender#2]
The math used to perform these two function are not the same. If you select an island or face and get the texel density, then click on apply to apply the texel density. You will see the size of island change. This should not be the case since you are applying the same texel density again.

Another test to perform is to apply a texel density of 100 then use the get texel density to check. I get a texel density of 264.09. I'm sure there is an error here but I'm not familiar enough to know which function is the one with the correct value.

**Comment by heclak** [comment]
Just noticed that it only happens when the object is not at a scale factor of 1. The apply function seems to be taking into account the scale factor but the get texel density function is not.

**Comment by juangea** [comment]
@heclak anything done inside Blender takes into account the scale of the object (as in any other software), not having the scale at 1,1,1 is problematic in general, if you have scale at 1,1,1 does the error appear?

Cheers.

**Comment by heclak** [comment]
nope. the problem doesn't exist at scale 1,1,1. Maybe it would help to pop up a warning if the scale isn't at 1,1,1? Since the values are incorrect in such a situation and the bug might not be obvious.

**Comment by juangea** [comment]
A warning could be interesting, but in reality this is something that is well known in general, one of the first things to check when something acts weird, it's the same for Maya or Max ir any other 3d software :)
