### ISSUE TITLE
Blender 4.0: Checker Map is always 512 despite choosing different resolutions.

### ISSUE THREAD

**Issue by lesgoo15** [franMarz/TexTools-Blender#202]
Since upgrading to Blender 4.0, when pressing Checker Map button, the checker map generated whether Mono, Color or Gravity is _always_ 512 pixel size. When different resolutions are selected, nothing changes. The checker map size still remains the same.

Other users also had the same issue:
https://www.reddit.com/r/blenderhelp/comments/1amul6q/anyone_using_textools_know_why_i_cant_get_it_to/

**Comment by franMarz** [comment]
That is intentional, visit [https://github.com/franMarz/TexTools-Blender/issues/187](https://github.com/franMarz/TexTools-Blender/issues/187). Closing
