### ISSUE TITLE
TexTools for Blender wrong unregistration when using Reload Scripts operator

### ISSUE THREAD

**Issue by Rawalanche** [franMarz/TexTools-Blender#203]
I am a addon developer and I use TexTools. When developing addons, I often reload scripts. I need the command line log to be clean so that I can see where the issue is when reloading my updated script. TexTools does not correctly unregister it's addon modules prior to reload which results in extreme pollution of the command line:
![image](https://github.com/franMarz/TexTools-Blender/assets/38806207/7a8bb2e0-5a92-4162-913b-801218153967)
This drowns any relevant messages in a big wall of text. I don't want to be disabling TexTools anytime I update my own scripts, especially since disabling addons in Blender usually destroys all the addon preferences, which have to be re-setup when reenabling the addon.

No other addon does this, so TexTools should not either. The command line log should remain clean after reloading addons.

**Comment by franMarz** [comment]
I never saw that I don't know why. Could you confirm if this is now fixed in master with the latest commit?

**Comment by franMarz** [comment]
I assume this is now fixed thanks to 5f0dc5921bcf78226e1f974b5a391bb14bdb5555, reopen otherwise.
