### ISSUE TITLE
Textools ver.1.6.1 not enabling in Blender 4.1.0

### ISSUE THREAD

**Issue by FehMello** [franMarz/TexTools-Blender#207]
I'm getting an error when marking the checkbox to enable the add-on in Blender 4.1.0. The images below shows the error log from Blender.
![image](https://github.com/franMarz/TexTools-Blender/assets/72583255/c916864c-bb88-4c03-aa26-3b226807788a)
![image](https://github.com/franMarz/TexTools-Blender/assets/72583255/080569c1-c1cd-4a93-8dec-8c1cb57c5e3a)

**Comment by franMarz** [comment]
It's not happening to me in Blender 4.1.1 after installing the latest version from master. Remember to previously uninstall any version of textools you have in Users\ _username_ \AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons

**Comment by franMarz** [comment]
It's not happening to me. Remember to previously delete/uninstall any version of TexTools you have in 
_C:\Users\Fefec\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\TexTools_ 
before installing the latest version of textools from master

**Comment by FehMello** [comment]
> It's not happening to me. Remember to previously delete/uninstall any version of TexTools you have in _C:\Users\Fefec\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\TexTools_ before installing the latest version of textools from master

I tried to install again, the exact same way I did before and now it worked. Maybe the last time there was some cache files or remnant files of the older Textools conflicting with the new one, idk. I did nothing different, it just worked.
