### ISSUE TITLE
size does not change

### ISSUE THREAD

**Issue by RatGrnn** [franMarz/TexTools-Blender#216]
i saw on reddit that people have this problem, but no one knows the solution

changing the size in textools, nothing changes, and the same checker remains 512x512

i have blender 4.1, but I also tested it on 3.2 and the checker remains 512x512 everywhere

**Comment by franMarz** [comment]
Can you share the link to that reddit discussion? Because I've closed two issues so far related to this and maybe I'm missing something here.

**Comment by misfit22** [comment]
> Can you share the link to that reddit discussion? Because I've closed two issues so far related to this and maybe I'm missing something here.

[https://www.reddit.com/r/blender/comments/1d5dhw9/i_cant_seem_to_get_textools_to_change_the_checker/](url)
[https://www.reddit.com/r/blenderhelp/comments/1amul6q/anyone_using_textools_know_why_i_cant_get_it_to/](url)

Hi!
i can also confirm, that feature does not work properly, stuck with 512x512 textures.
2nd topic is 4month old but someone commented recently.

**Comment by franMarz** [comment]
We can reimplement this with a new internal logic, with Custom Properties being added and removed per object to control the Checker Map tiling, avoiding shader or texture duplication.

**Comment by franMarz** [comment]
Please install and try the latest version of master. Could not be good enough if you need to set the Checker Map tiling of many objects, but I think it is a step in the right direction.

**Comment by misfit22** [comment]
> Please install and try the latest version of master. Could not be good enough if you need to set the Checker Map tiling of many objects, but I think it is a step in the right direction.

Maybe i'm doing something wrong? I see no change, got 512x512 textures:

![IMAG0044](https://github.com/franMarz/TexTools-Blender/assets/78850667/95f99129-95d8-4f04-9f00-6dca4e762f8e)

**Comment by franMarz** [comment]
I copy and paste here the description of the commit:

_Formerly controlled with the TexTools global resolution, now a Custom Property is added to every Object which has a Checker Map applied to tune the tiling (or projection Scale) of the Checker texture. For convenience, the value of this property for the Active Object is exposed in the Textools UI below the Checker Map button.
Now, the Viewport Shading Modes "Material Preview" or "Rendered" need to be in use to view the effect of the Checker Map Tiling._

**Just change the Tiling value which appears under the Checker Map button after being used. The resolution just controls the texture baking results, I changed that many commits ago for a number of reasons that are internal to the addon, to prevent adding garbage data to the blendfile in use, and to avoid interferences between the Baking and Checker Map operators**

**Comment by misfit22** [comment]
Yes tried to change the tiling to x10, yet it does not change anything.

**Comment by franMarz** [comment]
Can you share a screenshot like the one you posted before with the Tiling set to 10? Please note that the Checker image is not gonna change, it's the 3D preview of it what will change.

![blender_8PXlLSflrK](https://github.com/franMarz/TexTools-Blender/assets/58062362/adefb20b-c503-4826-ab34-446b6b2c9bbe)

**Comment by RatGrnn** [comment]
nothing changes
![image](https://github.com/franMarz/TexTools-Blender/assets/145942609/b2276069-c726-4bd2-b098-c5bf6bb413b7)

**Comment by franMarz** [comment]
I forgot to update the resources on master, please install the latest version and try again.

**Comment by RatGrnn** [comment]
yeah, tiling working now
is it possible to make the checker of the required size change itself when you change the size of the texture?

**Comment by franMarz** [comment]
I want to maintain the Resolution and the new Tiling parameters independent for people who use both Checker Maps and Baking. They are different concepts anyway.
If you need the Checker textures to have a base resolution bigger than 512px for some reason, you can always edit them. They are packed inside the materials_3.0.blend, which you can find in the Resources folder of the add-on.
This is a working first implementation, could be improved. For example, making the Tiling control the Checker projection scale of all selected objects, not just the Active one.

**Comment by franMarz** [comment]
Thank you for your insights, I think this is good enough for now. Closing

**Comment by DanielBonMar** [comment]
The tilling button never appears, is this normal or am I making a mistake?

<img width="1727" height="1003" alt="Image" src="https://github.com/user-attachments/assets/c7cf0a7d-614c-43c8-83e7-d7e872460c14" />
