### ISSUE TITLE
Color ID tab not working after updating to blender 4.2

### ISSUE THREAD

**Issue by Leonature26** [franMarz/TexTools-Blender#217]
When you click it nothing comes out. Other tabs work fine though. Tried to reinstall but still the same.

**Comment by Vlad21L** [comment]
same with me

**Comment by franMarz** [comment]
It works for me with [the latest version from master](https://github.com/franMarz/TexTools-Blender/archive/refs/heads/master.zip) ported from a previous installation. Are you using any uncommitted patch from bgteach or oxicid? The UI or Color ID tools haven't changed recently in master, and the 4.2 version of Blender works for me as before, plus I don't see any breaking changes in the API related to this in the Blender 4.2 release notes.

**Comment by Leonature26** [comment]
tried installing that one you linked and it's still the same. I don't know what "bgteach or oxicid" is so probably not. I tried opening it in 4.1 and it works.

**Comment by franMarz** [comment]
I can't reproduce the error, so I'll make a few questions:
It happens with any file?
Are you on Windows, Linux or MacOS?
Can you open the Console and see whether any exception message is printed at any point from the start of Blender to the manipulation of the Color ID Panel or tools?
Ultimately, can you please record a video of the screen for us to see what's happening?

**Comment by Leonature26** [comment]
-It happens with any file, even empty ones.
-Windows
-Console has no error message from start and upon pressing the color ID tab
-What's happening is simply the Color ID tab is not expanding upon pressing. It just changes the arrow icon from ">" to "v".
-One notable thing I can think of is I updated from steam and copied over the 4.1 appdata folder to 4.2.
Other than that, if there's no easy fix I'm fine with it. Other people facing the same issue might have more details.

**Comment by franMarz** [comment]
Thank you. This is happening to you because you have EEVEE as the render engine and it has been renamed internally to "BLENDER_EEVEE_NEXT", so some checks are misfiring silently is our code. I'll delete those checks as they are deprecated anyway.
