### ISSUE TITLE
UDIM support

### ISSUE THREAD

**Issue by kusogaki77** [franMarz/TexTools-Blender#22]
I updated to the latest textools yesterday.  Running Blender 2.83, I looked around for a way to specify what tile selected UVs should be cropped to, but couldn't find it.

Would it be possible to specify what UDIM tile a tex tool action (edge peel, crop, etc.) would apply to?

**Comment by SavMartin** [comment]
Not UDIM support yet, but you can use this one https://github.com/anfeo/blender_addon_bake_UDIM

**Comment by franMarz** [comment]
To be investigated.
