### ISSUE TITLE
Cage objects affect AO baking in single texture mode

### ISSUE THREAD

**Issue by sdml** [franMarz/TexTools-Blender#228]
Because cage object rendering is disabled or enabled for each bake set individually, the cage object from one set may be visible in the ambient occlusion (AO) of another object when baking to a single texture.
I fixed this issue on my end by moving the `hide_render=True` for cage objects before the main baking loop and setting `hide_render=False` in the "finally" block. However, I'm not sure if this solution works for all cases, and I'm not familiar enough with the addon to submit a pull request.

**Comment by franMarz** [comment]
The solution you described is the correct one for the issue you found, please open a pull request, I'll fix it further if needed.
Thank you.
