### ISSUE TITLE
Color Id tab does not work

### ISSUE THREAD

**Issue by NooBTvv2** [franMarz/TexTools-Blender#231]
[Edit] Just saw that this issue is already fixed, just downloaded the latest version from master and it now works. Sorry for creating this issue instance. 🙏

Clicking on the Color Id tab does not show anything.
Restarted and reinstalled the plugin and blender, still does not show anything

Blender Version: 4.2.2 LTS

![image](https://github.com/user-attachments/assets/bdb12c31-d093-41e0-8714-d208a1d09ded)

**Comment by franMarz** [comment]
No problem. Closing.
