### ISSUE TITLE
The Color ID tab is completely empty

### ISSUE THREAD

**Issue by Minsela** [franMarz/TexTools-Blender#244]
Hi, I am completely new at Blender (and asset creation) so I apologize if this is a miss on my part, but there is nothing under Color ID tab in any of my scenes. It's the same in a fresh new scene with the default cube in.

Any clues as to why this is the case? Am I missing a step?

![Screenshot 2024-11-04 120313](https://github.com/user-attachments/assets/2e9349c8-792f-4a49-b521-a653db9d1765)

**Comment by franMarz** [comment]
Hi there,

probably your issue is a duplicate of #231, #225 and #217. Please install [the latest version of TexTools from master](https://github.com/franMarz/TexTools-Blender/archive/refs/heads/master.zip) and tell me whether that solves your problem or not.

**Comment by Minsela** [comment]
Oh, thank you so much, that fixed it!

**Comment by franMarz** [comment]
You're welcome, @Minsela . Have a nice day.

**Comment by F3LiX-xai** [comment]
You save my day man AHAHAHA after I struggling for 2 days to find this solution
