### ISSUE TITLE
Cannot get anything to work

### ISSUE THREAD

**Issue by worsin** [franMarz/TexTools-Blender#27]
I know this sounds vague but literally nothing in this plugin works with my install.  I can see the menu but everything i try to use throws an error or does nothing but make islands vanish or parts of my mesh to be randomly deselected.  

None of the sorting works, clicking the buttons results in deselecting the islands and no sorting is done.

Reload Textures throws this error
https://i.imgur.com/6Xs1hqi.png

Spent about 30 min testing things and I was unable to get even 1 thing to work.  My only guess is that I have the wrong version or something. 

Here is my version
https://i.imgur.com/Lwv5BQ9.png

If this is not the right file a link to the correct one would be most appreciated.

**Comment by franMarz** [comment]
I don't have that error when reloading textures.
I see a weird message of "Upgrade to 2.8x required" on your screenshot that I don't get on my side (I'm using 2.82a)
Remove the add-on and then install this version, it's a couple of minutes anyway:
[MASTER](https://github.com/SavMartin/TexTools-Blender/archive/master.zip)
Please report any progress

**Comment by franMarz** [comment]
Ok, I got that error in the 2.90, because the Blender API has changed. Now you can't specify the height for the "invoke_popup" operator, only the width.
I'll make a push request for that. If you get other errors, please report them one by one and we can try to solve them. Without logs, we can do little to nothing.

**Comment by franMarz** [comment]
Sorting the islands (I think you mean Sort H and Sort V) works for me in 2.82a, 2.83 and 2.90. Maybe you can share with us the file where you have these issues?
Anyway, you don't have the latest version of the add-on, so my first message is still valid in that regard. Update the add-on.
