### ISSUE TITLE
Align World and Align Edge behaving differently on every version of Blender

### ISSUE THREAD

**Issue by franMarz** [franMarz/TexTools-Blender#32]
The current version of Align World works as expected in Blender 2.82 and 2.90.
For Blender 2.83, the rotation applied to every face/island is inverse, so the issue that made me write the comment "# minus angle; Blender uses unconventional rotation notation (positive for clockwise)" next to the malfunctioning line seemed to be tackled by the Core Developers. Removing the "-" in the two lines of the code solved it. The problem is that in 2.90, this doesn't work again and the current version of the script, with the minus, is which works, as I stated previously, so I don't know what they did.
Moreover, for version 2.91 none of the scripts, with or without minus, works, so other thing changed. The problem, as always, is the scarce documentation around the changes in the Blender API, so keeping track of them and adapting the addon accordingly is very difficult.
We can't have different versions of the addon just for this to work because they change how the UV mode behave back and forth between version, so we'll wait for 2.91 to be released to mess with the Align World operator unless we get to understand what is happening before then.

**Comment by franMarz** [comment]
We have a similar problem with Align Edge, maybe caused by the same changes in the code of Blender.
Align Edge works well in 2.83, but badly in 2.82, 2.90 and 2.91.

**Comment by SavMartin** [comment]
Already fixed, Thx @Symstract for your merge request.

**Comment by franMarz** [comment]
Align World still needs correction, I can try to apply the same solution to it.
