### ISSUE TITLE
Hard Crash when baking  8192

### ISSUE THREAD

**Issue by Opity69** [franMarz/TexTools-Blender#35]
blender 2.9 - crash when setting bake size to  8192 
also crashes  with 4046  at AA *4

also no way to tell a what stage the bake is.

**Comment by AvisParadocs** [comment]
Basically if you use AA its multiples your render resolution and then resizes image to your final output size. So 4k with AAx4 is 16k render image. It will render very long time and can crush due lack of memory size. Maybe my pull request can help you.

**Comment by Opity69** [comment]
I am having an issue with your pull request.
think you might have missed a  comma line 476__inint_.py
also after I quickly changed  it

also  bad indent in op_bake  line 543
cant bake at all now just gives a stack trace

**Comment by AvisParadocs** [comment]
My bad, it was syntax errors. You can try again. I've fixed my part.

**Comment by Opity69** [comment]
ill give it a go when I get sometime

**Comment by Opity69** [comment]
getting a different issue now  -   key error can't find  for collections when trying to bake

**Comment by AvisParadocs** [comment]
Comment lines 542-543 in op_bake.py and try again.

**Comment by Opity69** [comment]
found the actual issue -  its  a naming problem  -  file needs to be name textools in lower case or that cant get  the  addon propteries

**Comment by Opity69** [comment]
nothing to do with those lines

**Comment by Opity69** [comment]
doesn't fix my crash though 
also, is there some way to add baking progress bar its really annoying to just watch blender freeze and bake or crash

**Comment by Opity69** [comment]
more testing and it seem to be just normal map baking that crahses

**Comment by franMarz** [comment]
I made a series of test. Blender 2.91, last release of TexTools, windows 7, 32GB of system RAM.

It doesn't crash on my side, 8K normal map baking with no AA, peak of 12GB of system RAM used; 4K normal map baking with 4x AA (16K texture), peak of 49GB of system memory used (32GB/32GB of system RAM + 17GB virtual). Baking a 16K texture with the Blender operator last about the same and consumes almost the same amount of memory, with a peak of 48GB. The following, last method, is somehow so much faster as well: by running it from the Blender API with this simple script:
import bpy
bpy.ops.object.bake(type='NORMAL')
you get about the same result, with a peak memory usage of 46GB, but without progress bar; if you need the last, just use the Blender bake utility from the Render Properties tab.

As far, for me, this is not related to an addon shortcoming. Check your system virtual memory limits.

**Comment by Opity69** [comment]
thanks, I thought that was almost like  a memory issue, been having a similar issue with a standard blender,  my hard was also  getting  full so  virtual memory  issue  would  make a heap of sense

**Comment by franMarz** [comment]
You're welcome. If your issue persist, please reopen this report, or ask for it if you can't.
