### ISSUE TITLE
Ready for Blender 2.9 with optiX?

### ISSUE THREAD

**Issue by 3dcinetv** [franMarz/TexTools-Blender#38]
Hi, this addon is superb! I was wondering if this current version is supported on Blender 2.9? Specially with the denoising advantages for the Nvida graphics card?
Can I use this current version for Blender 2.9?

**Comment by SavMartin** [comment]
I don't know if with optiX it works fine, but at 2.90 and 2.91 it seems to work fine.

**Comment by franMarz** [comment]
Not on our side. The addon uses the same baking tools of Blender, controlled through the Python API. Currently, baking with OptiX is not possible in Blender. See:

[https://developer.blender.org/D9784](https://developer.blender.org/D9784)
