### ISSUE TITLE
Blender 2.90 - Baking Error

### ISSUE THREAD

**Issue by aprather51** [franMarz/TexTools-Blender#42]
Blender 2.90
Textool 1.3.0

First time using Textool, I understand I'd need to select cube_high and cube_low in order to bake any maps. But end up getting error. 
![Screenshot_1](https://user-images.githubusercontent.com/10257247/93718664-4a878f00-fb43-11ea-9785-16332fff3ea8.jpg)

This error apply to every baking map that I tried... Am I missing something?

**Comment by SavMartin** [comment]
You must download form here : https://github.com/SavMartin/TexTools-Blender/releases/download/exTools_2.8x/Textools.zip

**Comment by aprather51** [comment]
Great, it's working now... Thank you!
