### ISSUE TITLE
Original Material isn't restored when cycling Checker Maps

### ISSUE THREAD

**Issue by Michaelknubben** [franMarz/TexTools-Blender#44]
When clicking the 'Checker Map' button in the UV Editor, when it's gone through all three built-in options it leaves the mesh without an assigned material, even when the mesh original _did_ have one. As I recall this didn't happen in 2.79, where instead it restored the original material!
Is this a limitation or a bug?

edit: I'm on Blender 2.91.0 alpha, and 1.3.0 of the addon.

**Comment by franMarz** [comment]
It's a limitation for now, the code cleans the slot by default. Maybe we can have this done by storing the name of the material in the object properties and recovering-reasigning from there, but for objects with multiple materials, listing the materials applied to every face is needed as well.

**Comment by franMarz** [comment]
If we had material override on EEVEE, this issue could be solved in a more elegant way. Hope for this patch [https://developer.blender.org/D9143](https://developer.blender.org/D9143) to get worked on.

**Comment by Michaelknubben** [comment]
Yeah, I see the issue with multiple materials. Would it be possible though?
But agreed, a material override would be nice. But even better would be viewport visualisation modes related to unwrapping, such as the stretch preview in 3d, and checker maps!
