### ISSUE TITLE
Straight UV error

### ISSUE THREAD

**Issue by Kida-Maika** [franMarz/TexTools-Blender#47]
![image](https://user-images.githubusercontent.com/73355425/97026627-98edda80-1594-11eb-890e-7bfd5f7d22cf.png)

When I tried to flatten out something, TexTools give this error all of sudden. Also in the case when it works without the error (even my straighten edge was also flattened), it just doesn't work in correct way and mess up everything like below case.

Before straighten (I straightened current selected edge)

![image](https://user-images.githubusercontent.com/73355425/97027001-1ade0380-1595-11eb-99ab-843ec895f53a.png)

After straighten

![image](https://user-images.githubusercontent.com/73355425/97027061-31845a80-1595-11eb-9712-d72980cd2ad7.png)

I'm getting into TexTools recently. So I may misunderstand how to use it and use it wrong way. But I can't find any suitable solutions for this case, so I guess it's kinds of errors. Textools seems to be gonna my favorite tool. Hope it fixed soon!

**Comment by franMarz** [comment]
At least one error is related to Blender master changes, and I have a fix for it on my fork, I'll make a pusk request in the future, I need something else to be merged first. Unfortunately, other errors need further investigation, but seems that the script needs a better sorting of the problems that would arise when the selection is not a perfect loop or belongs to different islands... and probably more. Hopefully someone has more time than me to spend to solve this soon.

**Comment by franMarz** [comment]
This happens when you've selected a closed edge loop. I'll try to improve the script so that all the vertices in the edge loop but one will be pinned before the unwrap.
Anyway a complete rewrite seems to be needed as other parts of the script are behaving inconsistently and the code is a mess as it is now.

**Comment by franMarz** [comment]
Fixed in 7126c6fd58957edea4f2399d27dcb624713e4b48
