### ISSUE TITLE
Instal Bl 2.80 error (macOs older version)

### ISSUE THREAD

**Issue by winniejo** [franMarz/TexTools-Blender#49]
I get this message in Blender 2.8.0 what does this mean?

![error](https://user-images.githubusercontent.com/22052573/99686700-22a1a280-2a84-11eb-8c97-1d2930443c85.png)

Tryed both 2.8 zip and 2.8&2.9 zip version

**Comment by franMarz** [comment]
Isn't this related to #29 ? Latest release should work because of the patch #31 , but I don't know if there could be any issue specific to macOS and/or Blender 2.80.

**Comment by franMarz** [comment]
Please deactivate and uninstall your currently installed TexTools addon, install the [latest TexTools release](https://github.com/SavMartin/TexTools-Blender/releases/download/TexTools_2.9xb/TexTools.Blender.2.8x-2.9x.zip) preferably on the latest stable Blender version (2.91), and report if this is still happening.

**Comment by franMarz** [comment]
Closed because of inactivity.
