### ISSUE TITLE
"Bounds" button doesn't really do what the description says.

### ISSUE THREAD

**Issue by PabloCaracena** [franMarz/TexTools-Blender#51]
It selects the seams, not the islands bounds. And you can have islands in the UV without seams in the 3D model.

You could use the "bpy.ops.uv.seams_from_islands()" operator (Blender native) before the other operators to solve it. It would create seams that you may not want.

Other solution could be just change the description to "Select seams in UV map" or something like that.

Thanks for the addon again!

**Comment by franMarz** [comment]
It works as intended. You have to select the islands whose bounds you want to get selected. Please read #33

**Comment by PabloCaracena** [comment]
It may work as intended, but it does not select the islands bounds if they don't have seams in the 3D model.
It selects just the marked seams, in the UV map. That's why I say the description is not accurate.

VIDEO: https://youtu.be/gqvStF0ZCs8
I checked it with other 3D models too.

**Comment by franMarz** [comment]
Ok, I'm using 2.83.9 LTS. In 2.90/2.91 it doesn't work, as you say. Time to check the Blender API, again.

**Comment by franMarz** [comment]
[op_select_islands_outline.zip](https://github.com/SavMartin/TexTools-Blender/files/5587357/op_select_islands_outline.zip)

I fixed it for 2.90, but it doesn't work now for 2.83 neither 2.91. A lot of things are happening in the UV Editor nowadays, I'm out for now with this, have work to do these days. Good luck if you want to tackle this mess, totally unrelated to us, humble addon maintainers. Just make sure what you, or anyone else does, works on every version of Blender between 2.83 and the newest. Again, good luck with that.

**Comment by PabloCaracena** [comment]
Hi, fixed it. I checked in 2.83, 2.90 and 2.91. The only problem was creating seams from island after other operations, I moved "contextViewUV declaration", "Store previous edge seams" and "Create seams from islands" to the top of "def select_outline()", after the other needed declarations, and it works now. This is how it looks working for me:

def select_outline(context):

	#Only in Edit mode
	if bpy.context.active_object.mode != 'EDIT':
		bpy.ops.object.mode_set(mode='EDIT')
			
	bm = bmesh.from_edit_mesh(bpy.context.active_object.data);
	uv_layers = bm.loops.layers.uv.verify();
       

		
	contextViewUV = utilities_ui.GetContextViewUV()
	if not contextViewUV:
		self.report({'ERROR_INVALID_INPUT'}, "This tool requires an available UV/Image view.")
		return
		
	# Store previous edge seams
	edges_seam = [edge for edge in bm.edges if edge.seam]
	
	# Create seams from islands
	bpy.ops.uv.seams_from_islands(contextViewUV)
	edges_seams_from_islands = [edge for edge in bm.edges if edge.seam]

The rest of the script is the same, without the lines I moved obviously.

I tried doing a pull request with this fix, but I don't know Github, I'm not sure if I'm doing it right or what am I really doing at all. And I'm not a programmer, just code for fun sometimes, so sorry for this way of communicating bugs and fixes hahahaha. 

Thanks for maintaining the addon!!

**Comment by franMarz** [comment]
Well, not perfect but it is better the way you say.
It's not working as designed, because the lines that were placed before what you moved, whose purpose is consolidate the selection, have to be before the seams creation, or you get something weird if you don't select the islands entirely. We can make it as you propose, is working anyway, but a deeper evalution regarding why it wasn't working previously to find the cause of the error would conduct to a better solution. Anyway, we can consider that, if the islands were not well selected in the first place, it's up to the user and thus the outcome understantable and predictable, the UV Smooth you reported would also be fixed, previously both operators weren't working at all in every version so...
