### ISSUE TITLE
Available for Blender 2.92?

### ISSUE THREAD

**Issue by 3dcinetv** [franMarz/TexTools-Blender#60]
Hi. I've used TexTool over the 2.8x series. It's a very powerful addon.
Is there a chance to see it upgrade to be used in Blender 2.9x, please?
Thanks!

2.92 has a lot of speed optimizations that would combo fantastically with TexTool.

**Comment by franMarz** [comment]
No need for update, [latest release](https://github.com/SavMartin/TexTools-Blender/releases/download/TexTools_2.9x/TexTools-Blender.2.8x_2.9x.zip) is already working on 2.92 like in any other previous version.
