### ISSUE TITLE
Wrong Material ID Map baking output.

### ISSUE THREAD

**Issue by Losco-Nosciuto** [franMarz/TexTools-Blender#61]
![image](https://user-images.githubusercontent.com/35420766/102506421-5d96f600-4083-11eb-9c1b-ac58a9096ca1.png)
As can be seen here, Wrong Material ID palette is still being used, so bug still persist, making as now, ID making useless unless post-processed by hand on Photoshop.

The issue is not only in the discrepancy of the palette, but also with the actual colors used, which mostly are slightly different shades of the same 3 colors.

Result has been retried on all 3 my computers.

NVidia GPU / INTEL CPU
AMD GPU / INTEL CPU
NVidia GPU / AMD CPU

**Comment by franMarz** [comment]
You're not getting how Color ID works. you have to assign the color to your object/selected faces if you want them to be baked with the set of colors, and change the bake mode to diffuse. Not very useful, but works as originally designed (again, read [http://renderhjs.net/textools/blender/](http://renderhjs.net/textools/blender/))
Material ID is being reworked, until I don't test it properly, I won't update de addon. With the new code, the randomly assigned colors should be as different as possible from one another.

**Comment by franMarz** [comment]
You can test the future additions by installing this upcoming version of TexTools: [https://github.com/SavMartin/TexTools-Blender/archive/material-ID-fixes.zip](https://github.com/SavMartin/TexTools-Blender/archive/material-ID-fixes.zip). As I said, probably no bugs free for now.

**Comment by Losco-Nosciuto** [comment]
![image](https://user-images.githubusercontent.com/35420766/102627206-276f7a00-4148-11eb-8d4e-08a5f8c483f6.png)

Thanks for clarifying But I still get half baked maps, even tho materials are setup correctly. I removed all previously added materials, and assigned new colors from a clean mesh. Seems like it ignores 2 of 5

**Comment by franMarz** [comment]
Yes, but thas is a different problem now. I think that is a issue I noted a few days ago with diffuse baking, sometimes some materials are straight ignored, sometimes all objects are baked. It only happened to me in a multi-object bake setup. I'll dig into it soon.

**Comment by franMarz** [comment]
Fixed in the latest release.
