### ISSUE TITLE
1.4.0 not installing.

### ISSUE THREAD

**Issue by Losco-Nosciuto** [franMarz/TexTools-Blender#62]
This is the console output, seems no error is given

bpy.context.space_data.system_bookmarks_active = 3
Modules Installed () from 'E:\\USERS\\Downloads\\TexTools_v1.4.0.zip' into 'C:\\Users\\jmain\\AppData\\Roaming\\Blender Foundation\\Blender\\2.90\\scripts\\addons'
bpy.data.window_managers["WinMan"].addon_search = "tex"
Modules Installed () from 'E:\\USERS\\Downloads\\TexTools_v1.4.0.zip' into 'C:\\Users\\jmain\\AppData\\Roaming\\Blender Foundation\\Blender\\2.90\\scripts\\addons'

Seems like it installs in the root "Addon" folder instead of creating it's own subfolder, checking out rn

**Comment by Losco-Nosciuto** [comment]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'TexTools 1'

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'TexTools 1'



Installing manually outputs this

**Comment by franMarz** [comment]
Should be fixed now
