### ISSUE TITLE
Feature Request: 1.CUSTOME MARGIN for crop&fill, 2.ALIGN TOOL for UV island

### ISSUE THREAD

**Issue by jiabaoyu** [franMarz/TexTools-Blender#63]
Thank you dear developer of TexTool for making such a great tool for the community.
As a normal user, I really enjoy using this amazing addon!
Here's my personal feature request:
1. I do a lot of packaging work (especially a lot of paper boxes) and the CROP function in Textool helps me a lot. Basically I want make the most of my UV tile using CROP. In TexTools 1.3, I modified some code in the addon's python files to achieve 0 border margin for CROP. And I found that the border  margin setting was hard-coded. Could I expect a handy setting in the addon panel for user to determine the margin in percentage or pixel?
2.  TexTools already had vertical, horizontal and center align tool for vertices, edges and islands. It will be more convient if we could have left, right, top, bottom align tool, in combination with options for align target like align tool in Adobe illustrator. BTW align target means: we can choose to align selected UV to UV tile (the canvas) or just align to the active selection like how the addon behaves now. (to see how the align tool of illustrator works https://youtu.be/fT1VJV2M6_0?t=186)
Thank you again for reading my request ; )

**Comment by franMarz** [comment]
I'm not the original developer, just a maintainer, but I'll answer to you anyway as I'm mostly the one carrying this for the time being.
1. Under the TexTools subpanel (at the very top), set the Padding to 0.
2. It sounds interesting to add an option for aligning to UV Canvas and to Cursor in addition to the current "to selection". For the "align to key object type", which I think you're not even requesting, I have a few thoughts to share: active UV selection is not accesible from the Blender python API, so it would be needed to work with UV Sync Selection, that would bring issues with multi-object editing as multiple elements can be active at the same time. Besides, you can't select a whole island as active, we should determine the active island as the one having any active element, which is not very predictable. Therefore, I would discard the possibility of considering an active element as target, for now, for any TexTools operator.

**Comment by jiabaoyu** [comment]
> I'm not the original developer, just a maintainer, but I'll answer to you anyway as I'm mostly the one carrying this for the time being.
> 
> 1. Under the TexTools subpanel (at the very top), set the Padding to 0.
> 2. It sounds interesting to add an option for aligning to UV Canvas and to Cursor in addition to the current "to selection". For the "align to key object type", which I think you're not even requesting, I have a few thoughts to share: active UV selection is not accesible from the Blender python API, so it would be needed to work with UV Sync Selection, that would bring issues with multi-object editing as multiple elements can be active at the same time. Besides, you can't select a whole island as active, we should determine the active island as the one having any active element, which is not very predictable. Therefore, I would discard the possibility of considering an active element as target, for now, for any TexTools operator.

Appreciate your reply and thanks for your maintainess. What I am expecting most from request NO.2 is that left right up side down alignment to the canvas 😄
