### ISSUE TITLE
Explode button is greyed out

### ISSUE THREAD

**Issue by limarest** [franMarz/TexTools-Blender#67]
It seems like "explode" feature is always unavailable for me, even if I name meshes properly and organize them.
What could be the issue?

**Comment by Pratham-Dave** [comment]
Where exactly in the code have you implemented the  explode feature

**Comment by franMarz** [comment]
It works for me. "Explode" moves each baking set/group/pair apart from one another, of course only if you have multiple baking sets selected. This means you should get a "Bake >1x" text message in the Bake button for Explode to work. I think you're expecting a different behaviour, like separating high and low pairs, but that is not implemented neither planned to be.
