### ISSUE TITLE
Error con Rectify

### ISSUE THREAD

**Issue by gammafp** [franMarz/TexTools-Blender#68]
Blender 2.90.1
Cuando trato de hacer rectify a la siguiente pieza queda aplastada:
![image](https://user-images.githubusercontent.com/9221946/105075764-7e8ba600-5a8a-11eb-80fc-985c7cc306f6.png)

Con rectify: 
![image](https://user-images.githubusercontent.com/9221946/105075843-95ca9380-5a8a-11eb-93d0-228247d24d64.png)

El ejercicio con el que estoy tratando de desplegar UV es el siguiente: 
1) Abre el panel de UV Editing
2) Seleccionas la colección Low poly
3) Tratas de desplegar y se pueden realizar las pruebas ya que están realizadas las seams.

https://drive.google.com/file/d/1upeHvX0SbWk6BJA66AaeTajScNnlYFXy/view?usp=sharing

**Comment by franMarz** [comment]
Rectify no funciona bien con caras triangulares, está pensado para quads. Está basado en el addon UVSquares y es una limitación conocida y lógica. Igual que si no tienes quads en una pieza no puedes esperar poder seleccionar loops o rings, tampoco puedes esperar que funcione esto.
Gracias por el reporte de todas formas.
