### ISSUE TITLE
Align edge rotates island randomly in 2.92

### ISSUE THREAD

**Issue by radcapricorn** [franMarz/TexTools-Blender#72]
Well, subj. To reproduce, rotate UVs of default cube slightly and then attempt to align edge.

**Comment by xivader** [comment]
Is this fixed?

**Comment by franMarz** [comment]
Obviously, yes.
[https://github.com/SavMartin/TexTools-Blender/archive/master.zip](https://github.com/SavMartin/TexTools-Blender/archive/master.zip)

**Comment by xivader** [comment]
> 
> 
> Obviously, yes.
> https://github.com/SavMartin/TexTools-Blender/archive/master.zip

Thank you.
