### ISSUE TITLE
Baking single texture of multiple metallic objects gives incorrect result

### ISSUE THREAD

**Issue by sacrish** [franMarz/TexTools-Blender#76]
When baking a metallic map of more than 3 objects [edit: this issue can happen with 2 objects as well] with "Single Texture" ticked, only the first two objects get their metallic channel baked correctly. The other objects have their roughness baked instead.

![Screenshot 2021-03-31 170959](https://user-images.githubusercontent.com/8361680/113120249-fa049300-9243-11eb-9787-1bb28035aa5d.png)

Also If baking a base color map in this case, colors on the metallic part will be missing, and only the diffuse color gets baked.

![Screenshot 2021-03-31 171425](https://user-images.githubusercontent.com/8361680/113121177-f8879a80-9244-11eb-97b1-9e8478a17ef1.png)

**Comment by franMarz** [comment]
Not happening to me. Could you kindly share a file where this happens?

**Comment by sacrish** [comment]
Here in this blend file, the object "Metal2" cannot be correctly baked, even though it shares the same material with "Metal1".

[TexToolsTest.zip](https://github.com/SavMartin/TexTools-Blender/files/6235841/TexToolsTest.zip)

**Comment by sacrish** [comment]
Actually the "Single Texture" option doesn't matter. As long as 2 metallic objects are selected simultaneously, only one of them can be baked correctly. However, one non-metal and one metallic is fine.

**Comment by franMarz** [comment]
Ok, I can confirm the problem regarding objects sharing the same material. I'll investigate it.
Thank you for the report.
