### ISSUE TITLE
Rectify - Division by zero error

### ISSUE THREAD

**Issue by Gpinchon** [franMarz/TexTools-Blender#77]
When trying to do a "Rectify" operation on some meshes I get a "division by zero" error and it stops half-way...
[EDIT] [Here is the .blend with the problematic object](https://github.com/SavMartin/TexTools-Blender/files/6359173/TextoolsBug.zip)

**Comment by franMarz** [comment]
You have a ring of 64 zero edges in the inner border (i.e., two coincident boundary loops), so two have 64 faces of zero area. Disolve those edges or merge the duplicated vertices and the script shouldn't fail. Anyway, I noticed that the UV Squares addon doesn't fail here and the code should be the same, so something is missing in Rectify. It would be worth comparing both codes.
