### ISSUE TITLE
Mirror - Blender 3.0 - Error

### ISSUE THREAD

**Issue by Draise14** [franMarz/TexTools-Blender#78]
![image](https://user-images.githubusercontent.com/35357409/116488431-fde20000-a857-11eb-8b40-9a0ce30e3b01.png)

Al usar el Mirror V o H, se confunde el Proportional Edit, ya que no existe en el operador en Blender 3.0

**Comment by franMarz** [comment]
Thank you for the report.
We'll release a revised version of textools when Blender 3.0 is more stable (in bcon3 stage at least). Now, making any change may break backwards compatibility and we don't even know if the changes in current master are final.

**Comment by Karmacopper** [comment]
Issue is the same as reported here in 2.92.

**Comment by franMarz** [comment]
Can you confirm if this is solved in the latest version of [master](https://github.com/SavMartin/TexTools-Blender/archive/refs/heads/master.zip) for both 2.92 and 3.0, please?

**Comment by Karmacopper** [comment]
I can confirm this solves the issue in 2.92.

**Comment by franMarz** [comment]
3.0 should be fixed too, otherwise we can reopen this issue. Fixed by commit 9971a1489806782b2a397fa3d36f9538529c0309
