### ISSUE TITLE
Rotate 90° - Blender 3.0 - Error

### ISSUE THREAD

**Issue by Draise14** [franMarz/TexTools-Blender#79]
![image](https://user-images.githubusercontent.com/35357409/116488503-1fdb8280-a858-11eb-9d48-ff895b3402d3.png)

El version del Blender ha cambiado a dos caracteres, en vez de 3. Eso causa un error para rotar. Para arreglarlo hay que cambiar el `version_string` para convertir el string a float 

Usa en vez, esta:
`float(bpy.app.version_string[0:4].strip("."))`

**Comment by franMarz** [comment]
Thank you for the report and insights.
We'll release a revised version of textools when Blender 3.0 is more stable (in bcon3 stage at least). Now, making any change may break backwards compatibility and we don't even know if the changes in current master are final.
Our current goal must be to make TexTools stable in the next release of Blender, 2.93.

**Comment by Draise14** [comment]
You could make a versioning conditional to be backwards compatible. I saw this with the Modifier List addon. It falls back to old API if the version check is <= a certain version.
