### ISSUE TITLE
Color ID - Dropdown to Directly Assign Color to Vertex

### ISSUE THREAD

**Issue by zaha** [franMarz/TexTools-Blender#82]
Hi everyone,

gave some feedback in the Blenderartists thread but I thought it may be better to put it into its own issue here for visibility:

One thing I find a bit inconvenient is the way to create a color ID map based on vertex colors, which is my default workflow for working with Substance Painter:

1. When I have a mesh and am in the UV Editor, I go to the TexTools Color ID section.
2. I then select the parts of the mesh in the view I want to color and click on Assign Color for every part, which will create a material.
3. Then select everything and click Convert to: Vertex Color.

My suggestion is to add a dropdown there so I can select “Vertex Color” at the beginning and then directly “Assign Color” to my vertices, without having to go through materials and then converting it to vertex color.

**Comment by franMarz** [comment]
Added functionality by commit 72192a69ae674402354b4727e8262e90187811e0
