### ISSUE TITLE
Organize is broken but I think I fixed it here

### ISSUE THREAD

**Issue by CAPA14** [franMarz/TexTools-Blender#9]
When trying to press "Organize" an error pops up in line 100 of op_bake_organize_name.py

This line:
100			obj_B.name = utilities_bake.get_bake_name(obj_A)+" high"

The error complains about "utilities_bake.get_bake_name" which doesn't exist.

Digging a bit found the utilities_bake.py and indeed it doesn't exist or anywhere else in all files of te addon.

Not sure if it's the right thing to do but, I changed get_bake_name to get_set_name instead.
Then it worked to renaming the stuff and matching the HP to LP names.

This is broken in 1.3 version for 2.79 and 2.8

**Comment by AvisParadocs** [comment]
**Thanks!** That actually fixes an issue. Now organize is working for me too. Maybe you should make a pull request.

**Comment by CAPA14** [comment]
Good to know! @AvisParadocs 

How should I do this? I need to Fork commit to it and Request Pull from there?

**Comment by AvisParadocs** [comment]
I believe so.

**Comment by schroef** [comment]
You did not make a pull request yet correct?

**Comment by CAPA14** [comment]
Nope. I did not requested the pull. 

Actually made my fork and branch, tested some stuff and forgot :D 

Em 23/11/2019 15:17, schroef escreveu: 

> You did not make a pull request yet correct? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

 

Links:
------
[1]
https://github.com/SavMartin/TexTools-Blender/issues/9?email_source=notifications&amp;email_token=AGCZISIO43F4BYER5TNKW73QVFXUZA5CNFSM4JE6LZM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEE72W6A#issuecomment-557820792
[2]

**Comment by SavMartin** [comment]
@CAPA14 Thx for your help to fix this issue, I fix the line.
