### ISSUE TITLE
How to use the Explode feature?

### ISSUE THREAD

**Issue by yxx10** [franMarz/TexTools-Blender#92]
On the **Baking** field, there's an option called _Explode_. According to the original documentation, it "_moves all selected bake pairs apart into 6 directions._". Seems that it used to work with the groups feature (which as far as I remember, it was replaced with collections). So...does _Explode_ still works? and if so, how is it used? Thanks!

**Comment by franMarz** [comment]
It works for me. "Explode" moves each baking set/group/pair apart from one another, of course only if you have multiple baking sets selected. This means you should get a "Bake >1x" text message in the Bake button (with bake single uncheked) for Explode to work. I think you're expecting a different behaviour, like separating high and low pairs, but that is not implemented neither planned to be.

**Comment by Cl1nk** [comment]
In Blender 3.1.2 the explode button will create keyframes and jump to the frame 50 in the timeline but it wont move the objects, all of them remain at their previous position.

I tried the same scene on blender 2.93 with the 1.4.4 version an it works flawlessly. 

I don't see any error messages on blender 3.1.2

**Comment by franMarz** [comment]
> In Blender 3.1.2 the explode button will create keyframes and jump to the frame 50 in the timeline but it wont move the objects, all of them remain at their previous position.
> 
> I tried the same scene on blender 2.93 with the 1.4.4 version an it works flawlessly.
> 
> I don't see any error messages on blender 3.1.2

You should have created a new issue, your post got unnoticed to me until now.
