### ISSUE TITLE
Paint Base Rendering weirdly?

### ISSUE THREAD

**Issue by JustLluiji** [franMarz/TexTools-Blender#93]
For some reason the Paint Base baking option bugs out on some models. And in result, creates this weirdly shaded texture of the mesh rather than what it was supposed to render. Normals are fine and nothing else is in the scene besides the mesh. I tried other settings to see if it'll fix it but nothing worked.
![Problem](https://user-images.githubusercontent.com/42986718/126244886-000b3326-f151-4ef3-846f-ef44c96d98bd.PNG)
There's also nothing on the mesh itself that could be causing it.
![image](https://user-images.githubusercontent.com/42986718/126245004-78c9e58d-423a-4d30-8f55-f8305d090760.png)

**Comment by franMarz** [comment]
What do you expect this bake mode to deliver?

**Comment by JustLluiji** [comment]
I usually get a nice rendered texture I can start off editing into something more. Like this:
![image](https://user-images.githubusercontent.com/42986718/126258684-a4fddb32-1a8a-4fbc-9652-4a3db4a5c87e.png)

That I could turn into something like this:
![image](https://user-images.githubusercontent.com/42986718/126258743-df56b854-5395-4856-8722-de14a1aeb0b8.png)

But on this model I am working on right now, the bake mode somewhat refuses to render the shading correctly and gives me this weird gradient outcome.

**Comment by JustLluiji** [comment]
I also tried oversimplifying the model to see if it's the mesh and I also remade the bottom part. But still the same outcome.

![image](https://user-images.githubusercontent.com/42986718/126259384-45ed5bb9-0215-4d0b-88a3-03f98aa98963.png)

**Comment by franMarz** [comment]
From the original author [wiki](http://renderhjs.net/textools/blender/):
_"Sometimes also referred to Blizzard or Dota diffuse map. This bake combines a dirt map with vertical gradient and top facing normals with a highlight."_

From my standpoint, that is what you're getting. A different thing is whether you like it or not depending in the model topology. Maybe the highlight part is overexposed here, maybe the threshold to determine which faces are pointing up is a bit too sharp, but I don't really know what you are after.

This mode, like any other custom baking mode within this addon, uses custom materials temporarily applied to the bake object. Those materials are loaded from a file named "materials.blend" that you can find in "C:\Users\_yourUsername_\AppData\Roaming\Blender Foundation\Blender\_2.93_\scripts\addons\TexTools_1_4_4\resources". Select the "bake_paint_base" material and edit it. You can see the changes in real time in the 3D viewport below, applied to a weird preview object. Even append your dress here and use it to preview what you'll get, the meshes saved within this file will be ignored when loading the custom materials. Save the changes and bake using TexTools again in your original file.

**Comment by JustLluiji** [comment]
After some fiddling. For some reason the dark part refuses to change even if I put it at the lightest shade I can before it's entirely white. In the end, I ended up merging different paint base renders instead. Sorry for the inconvenience.

**Comment by franMarz** [comment]
Weird. I only found problems with inverted normals. If you want and can share the blendfile, I can investigate it further. Anyway, we can always reopen this if we discover a bug in the material or the bake code related to this.
