### ISSUE TITLE
does textools wrap work in blender 2.91/3 and blender v3 experimental

### ISSUE THREAD

**Issue by ringusd** [franMarz/TexTools-Blender#99]
hi, esteemed coders
does textools wrap work in blender v2.91/3 and blender v3 experimental, with textools 1.4.4
(it appeared in blender v2.79 textools v1.3 this version wrap worked)
in all versions with textools 1.4.4, i have tried the wrap button appears dark milky greyed out,
ie not a light normal grey button like uv mesh,
i have tried various combinations of selecting uvmesh and geo i wish to wrap, but the
wrap button never switches to on useable state.

**Comment by franMarz** [comment]
This will be tackled for the next release of TexTools, 1.5
